//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinApp.API {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pracownik", Namespace="http://schemas.datacontract.org/2004/07/KadetServiceProject")]
    [System.SerializableAttribute()]
    public partial class Pracownik : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NazwiskoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PeselField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Imie {
            get {
                return this.ImieField;
            }
            set {
                if ((object.ReferenceEquals(this.ImieField, value) != true)) {
                    this.ImieField = value;
                    this.RaisePropertyChanged("Imie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nazwisko {
            get {
                return this.NazwiskoField;
            }
            set {
                if ((object.ReferenceEquals(this.NazwiskoField, value) != true)) {
                    this.NazwiskoField = value;
                    this.RaisePropertyChanged("Nazwisko");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Numer {
            get {
                return this.NumerField;
            }
            set {
                if ((object.ReferenceEquals(this.NumerField, value) != true)) {
                    this.NumerField = value;
                    this.RaisePropertyChanged("Numer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pesel {
            get {
                return this.PeselField;
            }
            set {
                if ((object.ReferenceEquals(this.PeselField, value) != true)) {
                    this.PeselField = value;
                    this.RaisePropertyChanged("Pesel");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="API.IKadryService")]
    public interface IKadryService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKadryService/DodajPracownika", ReplyAction="http://tempuri.org/IKadryService/DodajPracownikaResponse")]
        WinApp.API.Pracownik DodajPracownika(WinApp.API.Pracownik pracownik, string haslo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKadryService/DodajPracownika", ReplyAction="http://tempuri.org/IKadryService/DodajPracownikaResponse")]
        System.Threading.Tasks.Task<WinApp.API.Pracownik> DodajPracownikaAsync(WinApp.API.Pracownik pracownik, string haslo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKadryService/ModyfikujPracownika", ReplyAction="http://tempuri.org/IKadryService/ModyfikujPracownikaResponse")]
        void ModyfikujPracownika(WinApp.API.Pracownik pracownik, string pesel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKadryService/ModyfikujPracownika", ReplyAction="http://tempuri.org/IKadryService/ModyfikujPracownikaResponse")]
        System.Threading.Tasks.Task ModyfikujPracownikaAsync(WinApp.API.Pracownik pracownik, string pesel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKadryService/UsunPracownika", ReplyAction="http://tempuri.org/IKadryService/UsunPracownikaResponse")]
        void UsunPracownika(string pesel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKadryService/UsunPracownika", ReplyAction="http://tempuri.org/IKadryService/UsunPracownikaResponse")]
        System.Threading.Tasks.Task UsunPracownikaAsync(string pesel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKadryService/WyszukajPracownika", ReplyAction="http://tempuri.org/IKadryService/WyszukajPracownikaResponse")]
        WinApp.API.Pracownik[] WyszukajPracownika(string fraza);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKadryService/WyszukajPracownika", ReplyAction="http://tempuri.org/IKadryService/WyszukajPracownikaResponse")]
        System.Threading.Tasks.Task<WinApp.API.Pracownik[]> WyszukajPracownikaAsync(string fraza);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IKadryServiceChannel : WinApp.API.IKadryService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KadryServiceClient : System.ServiceModel.ClientBase<WinApp.API.IKadryService>, WinApp.API.IKadryService {
        
        public KadryServiceClient() {
        }
        
        public KadryServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KadryServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KadryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KadryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WinApp.API.Pracownik DodajPracownika(WinApp.API.Pracownik pracownik, string haslo) {
            return base.Channel.DodajPracownika(pracownik, haslo);
        }
        
        public System.Threading.Tasks.Task<WinApp.API.Pracownik> DodajPracownikaAsync(WinApp.API.Pracownik pracownik, string haslo) {
            return base.Channel.DodajPracownikaAsync(pracownik, haslo);
        }
        
        public void ModyfikujPracownika(WinApp.API.Pracownik pracownik, string pesel) {
            base.Channel.ModyfikujPracownika(pracownik, pesel);
        }
        
        public System.Threading.Tasks.Task ModyfikujPracownikaAsync(WinApp.API.Pracownik pracownik, string pesel) {
            return base.Channel.ModyfikujPracownikaAsync(pracownik, pesel);
        }
        
        public void UsunPracownika(string pesel) {
            base.Channel.UsunPracownika(pesel);
        }
        
        public System.Threading.Tasks.Task UsunPracownikaAsync(string pesel) {
            return base.Channel.UsunPracownikaAsync(pesel);
        }
        
        public WinApp.API.Pracownik[] WyszukajPracownika(string fraza) {
            return base.Channel.WyszukajPracownika(fraza);
        }
        
        public System.Threading.Tasks.Task<WinApp.API.Pracownik[]> WyszukajPracownikaAsync(string fraza) {
            return base.Channel.WyszukajPracownikaAsync(fraza);
        }
    }
}
